// InvoiceBridge — GST Invoice PDF Generator (ported from Next.js)
import type { ConvertedInvoiceData } from "./converter";

const BLUE = "#1d4ed8";
const LIGHT_BLUE = "#dbeafe";
const DARK = "#1e293b";
const GRAY = "#64748b";
const LIGHT_GRAY = "#f8fafc";
const WHITE = "#ffffff";
const BORDER = "#e2e8f0";

function formatINR(amount: number): string {
  return new Intl.NumberFormat("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount);
}

function todayFull(): string {
  return new Date().toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
}

export async function generateGSTInvoicePDF(data: ConvertedInvoiceData): Promise<Buffer> {
  const PDFDocument = (await import("pdfkit")).default;

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 40,
      info: {
        Title: `GST Invoice - ${data.invoiceNumber}`,
        Author: "InvoiceBridge",
        Subject: "Indian GST Tax Invoice",
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - 80;
    const left = 40;
    let y = 40;

    // Header
    doc.rect(left, y, pageWidth, 60).fill(BLUE);
    doc.fillColor(WHITE).fontSize(22).font("Helvetica-Bold").text("TAX INVOICE", left + 10, y + 10, { width: pageWidth / 2 });
    doc.fillColor(LIGHT_BLUE).fontSize(10).font("Helvetica").text("Generated by InvoiceBridge", left + pageWidth / 2, y + 12, { width: pageWidth / 2, align: "right" });
    doc.fillColor(WHITE).fontSize(9).text("AI-Powered Invoice Conversion Platform", left + pageWidth / 2, y + 25, { width: pageWidth / 2, align: "right" });
    y += 70;

    const colMid = left + pageWidth / 2 + 10;
    const sectionTop = y;

    doc.fillColor(GRAY).fontSize(8).font("Helvetica-Bold").text("SELLER / FROM", left, y);
    y += 12;
    doc.fillColor(DARK).fontSize(9).font("Helvetica-Bold").text(data.seller.name, left, y);
    y += 12;
    doc.fillColor(GRAY).fontSize(8).font("Helvetica").text(data.seller.address, left, y, { width: pageWidth / 2 - 20 });
    y = doc.y + 6;
    doc.fillColor(DARK).fontSize(8).text(`GSTIN: ${data.seller.gstin}`, left, y);
    y += 14;

    doc.fillColor(GRAY).fontSize(8).font("Helvetica-Bold").text("BUYER / BILL TO", left, y);
    y += 12;
    doc.fillColor(DARK).fontSize(9).font("Helvetica-Bold").text(data.buyer.name, left, y);
    y += 12;
    doc.fillColor(GRAY).fontSize(8).font("Helvetica").text(data.buyer.address, left, y, { width: pageWidth / 2 - 20 });
    y = doc.y + 6;
    if (data.buyer.gstin) {
      doc.fillColor(DARK).fontSize(8).text(`GSTIN: ${data.buyer.gstin}`, left, y);
      y += 14;
    }

    const rightTop = sectionTop;
    const rLeft = colMid;
    const rWidth = pageWidth / 2 - 10;

    doc.rect(rLeft - 5, rightTop - 5, rWidth + 5, 130).fill(LIGHT_GRAY).stroke(BORDER);

    const invoiceDetails: [string, string][] = [
      ["Invoice No.", data.invoiceNumber],
      ["Invoice Date", data.invoiceDate],
      ["Original Invoice", data.originalInvoiceNumber],
      ["Place of Supply", `${data.placeOfSupply} (${data.stateCode})`],
      ["Supply Type", data.supplyType === "inter-state" ? "Inter-State" : "Intra-State"],
      ["Reverse Charge", data.reverseCharge ? "Yes" : "No"],
    ];

    let rY = rightTop + 5;
    for (const [label, value] of invoiceDetails) {
      doc.fillColor(GRAY).fontSize(7.5).font("Helvetica-Bold").text(label, rLeft, rY, { width: rWidth / 2 });
      doc.fillColor(DARK).fontSize(7.5).font("Helvetica").text(value, rLeft + rWidth / 2, rY, { width: rWidth / 2, align: "right" });
      rY += 18;
    }

    doc.fillColor(GRAY).fontSize(7).text(`Original: ${data.originalCurrency} -> INR @ ${data.exchangeRate}`, rLeft, rY, { width: rWidth });
    y = Math.max(y, rightTop + 145);

    // Line items table
    y += 10;
    const isInterState = data.supplyType === "inter-state";

    doc.rect(left, y, pageWidth, 18).fill(BLUE);

    const colWidths = isInterState
      ? [20, 130, 45, 30, 60, 70, 40, 50, 65]
      : [20, 110, 45, 30, 55, 65, 35, 45, 35, 45, 65];

    const colHeaders = isInterState
      ? ["#", "Description", "HSN/SAC", "Qty", "Rate (Rs)", "Taxable (Rs)", `IGST\n${data.gstRate}%`, "Tax (Rs)", "Total (Rs)"]
      : ["#", "Description", "HSN/SAC", "Qty", "Rate (Rs)", "Taxable (Rs)", `CGST\n${data.gstRate / 2}%`, "CGST (Rs)", `SGST\n${data.gstRate / 2}%`, "SGST (Rs)", "Total (Rs)"];

    let xPos = left;
    doc.fillColor(WHITE).fontSize(7).font("Helvetica-Bold");
    for (let i = 0; i < colHeaders.length; i++) {
      doc.text(colHeaders[i], xPos + 2, y + 3, { width: colWidths[i] - 4, align: i >= 3 ? "right" : "left" });
      xPos += colWidths[i];
    }
    y += 20;

    for (const item of data.lineItems) {
      const rowHeight = 22;
      const rowBg = data.lineItems.indexOf(item) % 2 === 0 ? WHITE : LIGHT_GRAY;
      doc.rect(left, y, pageWidth, rowHeight).fill(rowBg).stroke(BORDER);

      const rowData = isInterState
        ? [String(item.sno), item.description, item.hsnCode, String(item.quantity), formatINR(item.rateINR), formatINR(item.taxableValueINR), `${data.gstRate}%`, formatINR(item.igstAmount ?? 0), formatINR(item.totalINR)]
        : [String(item.sno), item.description, item.hsnCode, String(item.quantity), formatINR(item.rateINR), formatINR(item.taxableValueINR), `${data.gstRate / 2}%`, formatINR(item.cgstAmount ?? 0), `${data.gstRate / 2}%`, formatINR(item.sgstAmount ?? 0), formatINR(item.totalINR)];

      xPos = left;
      doc.fillColor(DARK).fontSize(7.5).font("Helvetica");
      for (let i = 0; i < rowData.length; i++) {
        doc.text(rowData[i], xPos + 2, y + 6, { width: colWidths[i] - 4, align: i >= 3 ? "right" : "left" });
        xPos += colWidths[i];
      }
      y += rowHeight;
    }

    // Tax summary
    y += 10;
    const summaryLeft = left + pageWidth / 2;
    const summaryWidth = pageWidth / 2;

    const summaryRows: [string, string][] = [
      ["Subtotal (Taxable Value)", `Rs ${formatINR(data.subtotalINR)}`],
    ];

    if (isInterState) {
      summaryRows.push([`IGST @ ${data.gstRate}%`, `Rs ${formatINR(data.igstAmount)}`]);
    } else {
      summaryRows.push([`CGST @ ${data.gstRate / 2}%`, `Rs ${formatINR(data.cgstAmount)}`]);
      summaryRows.push([`SGST @ ${data.gstRate / 2}%`, `Rs ${formatINR(data.sgstAmount)}`]);
    }

    summaryRows.push(["Total Tax", `Rs ${formatINR(data.totalTaxINR)}`]);
    if (Math.abs(data.roundOffINR) > 0) {
      summaryRows.push(["Round Off", `Rs ${formatINR(data.roundOffINR)}`]);
    }

    for (const [label, value] of summaryRows) {
      doc.rect(summaryLeft, y, summaryWidth, 16).fill(LIGHT_GRAY).stroke(BORDER);
      doc.fillColor(GRAY).fontSize(8).font("Helvetica").text(label, summaryLeft + 5, y + 4, { width: summaryWidth / 2 });
      doc.fillColor(DARK).fontSize(8).font("Helvetica-Bold").text(value, summaryLeft + summaryWidth / 2, y + 4, { width: summaryWidth / 2 - 5, align: "right" });
      y += 18;
    }

    doc.rect(summaryLeft, y, summaryWidth, 22).fill(BLUE);
    doc.fillColor(WHITE).fontSize(10).font("Helvetica-Bold").text("GRAND TOTAL", summaryLeft + 5, y + 6, { width: summaryWidth / 2 });
    doc.fillColor(WHITE).fontSize(10).font("Helvetica-Bold").text(`Rs ${formatINR(data.totalAfterRoundOffINR)}`, summaryLeft + summaryWidth / 2, y + 6, { width: summaryWidth / 2 - 5, align: "right" });
    y += 28;

    // Amount in words
    y += 8;
    doc.rect(left, y, pageWidth, 20).fill(LIGHT_BLUE).stroke(BORDER);
    doc.fillColor(BLUE).fontSize(8).font("Helvetica-Bold").text("Amount in Words: ", left + 5, y + 6, { continued: true }).font("Helvetica").fillColor(DARK).text(data.amountInWords);
    y += 28;

    // Footer
    doc.fillColor(GRAY).fontSize(7).font("Helvetica-Bold").text("Terms & Conditions", left, y);
    y += 10;
    doc.fillColor(GRAY).fontSize(7).font("Helvetica").text("1. This is a computer-generated GST invoice.\n2. All disputes subject to jurisdiction.\n3. Payment due within 30 days of invoice date.", left, y, { width: pageWidth / 2 });

    const sigRight = left + pageWidth / 2 + 20;
    doc.fillColor(GRAY).fontSize(7).font("Helvetica-Bold").text("For " + data.seller.name, sigRight, y, { width: pageWidth / 2 - 20 });
    doc.moveDown(3);
    doc.fillColor(DARK).fontSize(7).text("Authorized Signatory", sigRight, doc.y, { width: pageWidth / 2 - 20 });

    doc.fillColor(BORDER).fontSize(7).font("Helvetica").text(
      `Generated by InvoiceBridge on ${todayFull()} | Original: ${data.originalCurrency} ${data.originalTotal.toFixed(2)} @ ${data.exchangeRate} INR/USD`,
      left, doc.page.height - 30, { width: pageWidth, align: "center" }
    );

    doc.end();
  });
}
